name: Extract a Zip File
on:
    push:
        paths:
            - 'your-artifact/**.zip'
    workflow_dispatch:

jobs:
    unzip-job:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Print Environment Variables
              run: printenv

            - name: Unzip the file
              working-directory: your-artifact
              run: |
                filename=$(basename -s .zip *.zip)
                echo $filename